### ISSUE TITLE
Trouble with generic parameters

### ISSUE THREAD

**Issue by bbarker** [alecdotninja/tailcall#9]
See discussion on [this SO post](https://stackoverflow.com/questions/66424121/what-is-the-issue-with-passing-an-iterator-value-into-a-closure-expected-type). I'm not immediately sure of the best way to deal with this.

**Comment by alecdotninja** [comment]
This was fixed via #11 which was released in [v0.1.5](https://crates.io/crates/tailcall/0.1.5). Thank you for all of your help here, @bbarker !
